version: '3.5'
services:

  ssr-2:
    image: node:14
    container_name: ssr-2
    volumes:
      - "./:/app"
    command: bash -c "cd /app && npm i && npm run build:ssr && npm run serve:ssr "
    ports:
      - "4011:4000"
